version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./../www/AccreditedPrograms:/var/www/
      - ./nginx/conf.d:/etc/nginx/conf.d
    container_name: nginx_con
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./../www/AccreditedPrograms:/var/www
    depends_on:
      - mysql
    container_name: app_con

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: mysql_con